### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by MeetDhruv** [BitGo/BitGoJS#101]
I am unable to identify using webhook  for receiving coins. As i have 100 users ad they have send coins to bitgo address, however i am unable to identify that which address have received the coins as webhook notification is only providing the wallet id and not the receiving address. Please guide

**Comment by thomas4019** [comment]
The webhook response provides the transaction id which you can then lookup in our system. It is not as simple as just specifying the receiveAddress because you could receive in multiple addresses in the same transaction

Once you fetch you can determine if it's a receive transaction via the following.
1. Loop through all the entries that have a negative "value".
2. Use our API to determine if that address is in your wallet.
3. If any of the from addresses are part of your wallet then it's a send, otherwise it's a receive.

You can do something similar looking at the positive value entries with addresses that belong to the wallet to see which addresses were sent to. Note that addresses in chain 1 or 11 are change output and are generally not funds that were received from external users.

**Comment by MeetDhruv** [comment]
Hi Thomas,

Thank you for the response. Really appreciated.

Requesting you to help us with your API where we can integrate and fetch the details accordingly.

Also if you can help me with the sample code using the above parameters you said where we can identify the details, it would be a great help.

Awaiting response.

**Comment by bobozar** [comment]
@MeetDhruv  create a url function in your app, set the url in the webhook, put numconfirmations to at least 2(read the docs), so when a transaction comes in, BITGO will call ur url and in that url function in your code, ensure you get the data BITGO sends, maybe with bitgodata= json.loads(request.body) [I'm using Python] and get the tx value and lookup on the tx value via bitgo api [check the doc], so you should now get the btc address and value sent. and lookup for the address in your DB and fix the amount there. You can do anything you like. This should help you out.

**Comment by LeoKotschenreuther** [comment]
@MeetDhruv Sounds like your question has been answered well. Please reopen if you feel like that is not the case.
