### ISSUE TITLE
Can't generate eth wallet via api v2

### ISSUE THREAD

**Issue by MariKiev** [BitGo/BitGoJS#103]
data = {'label': 'Test - General API', 'passphrase': 'aEUY48d83sFdfsFdfa', 'enterprise': settings.enterprise_id}

"POST /api/v2/eth/wallet/generate HTTP/1.1" 401 173 "

Response:
{'error': 'cannot access this route with coin type eth',
 'message': 'cannot access this route with coin type eth',
 'name': 'Unauthorized',
 'requestId': 'cje7hem669cs57gld9ktjwim4'}

**Comment by thomas4019** [comment]
Hi Mari,
BitGo ETH and XRP wallets are currently only available for enterprise customers who have signed a contract. Please reach out to sales@bitgo.com for info about how to get access to ETH wallets if you need it.

**Comment by MariKiev** [comment]
We have a signed contract. 
And  ETH wallet which was created at dashboard doesn't work with api Bitgo express v2.

We receive an error, but password was double checked:
{'error': '(object_error) {"message":"password error - ccm: tag doesn\'t match","status":400}',
 'message': '(object_error) {"message":"password error - ccm: tag doesn\'t match","status":400}'}

**Comment by jstunich** [comment]
Hello Mari, 

We see that you have an account with bitgo, would you be so kind as to forward this issue to our support department so that we can track it and get more information there. Things we will need you to supply include the username, enterprise ID and the wallet ID that you are attempting to access. Thanks for reaching out and we will speak with you there.

-Justin

**Comment by nandishdave747** [comment]
Hi Mari,

Please meet Will and remove this issue from GitHub. Will should be able to give you the reason of removing this issue from GitHub. I have replied to Will on Freshdesk ticket. Thank you.

-Nandish
