### ISSUE TITLE
BTC -> Send Transaction to Many -> feeRate?

### ISSUE THREAD

**Issue by izhtrade** [BitGo/BitGoJS#122]
Hi

There is some misunderstanding on our part, when using the Send Transaction to Many method (/api/v2/:coin/wallet/:id/ sendmany) when sending Bitcoin, namely when we specify feeRate to 10000 in the parameter feeRate. ~ 10 sat / b

When viewing the transaction, through the API, its size is 214 bytes, with a commission of 2234 sat, which seems to be consistent, but when viewed through any browser it can be seen that the cost has been reduced by 2 times (~ 5 sat / b) and the size has increased to ~ 400

["feeString"] => string (4) "2234"
["size"] => int (214)

https://testnet.blockchain.info/tx/674df6160a44925534366e732e04031ee941bfafdb1873f91d0e21cb190813c5

It would be nice to find an explanation for this behavior)

Thank you.

**Comment by thomas4019** [comment]
Hi izhtrade,
This transaction is spending a segwit input which means fees are calculated based on the vsize rather than the actual blockchain size. In the API, when size is used, it's referring to the vsize. Some block explorers don't make that distinction clear, but smartbit shows both size and vsize.
https://testnet.smartbit.com.au/tx/674df6160a44925534366e732e04031ee941bfafdb1873f91d0e21cb190813c5
Other resources
https://blog.bitgo.com/transactions-are-getting-cheaper-segwit-now-on-bitgo-fe445e4f7f50
https://blog.bitgo.com/bitgo-segwit-launch-4732163d2c7f
If you have further questions, please send an email to support@bitgo.com
