### ISSUE TITLE
[Error] Non-base58 character, When wallet.signTransaction() is called.

### ISSUE THREAD

**Issue by flavioespinoza** [BitGo/BitGoJS#127]
I'm trying to send TBTC from one of my wallets to the other, and keep getting this error when I run the 'wallet.signTransaction()' method:

This is what is printed in the Node debugger.
![screen shot 2018-06-12 at 2 32 25 pm 2](https://user-images.githubusercontent.com/2214913/41315684-78929b22-6e4d-11e8-9eed-bb9bd1069620.png)

Here is a Gist with my entire Node server code:  https://gist.github.com/flavioespinoza/4f17076a4f6ec6bf1449dc6b0f174e3c

I've sent TBTC to these addresses on testnet and they work fine.  Any guidance would be much appreciated! :) Thanks!

**Comment by thomas4019** [comment]
Hi Flavio, are you sure you're passing an xprv to signTransaction? The first 4 characters should be "xprv" not some encrypted JSON blob.

Also, note that instead of calling build, sign and send, it's generally easier to just call the helper function [sendTransaction](https://www.bitgo.com/api/v2/#send-transaction) and pass either the walletPassphrase or prv.
