### ISSUE TITLE
Bitgo on-chain transaction

### ISSUE THREAD

**Issue by fessor10** [BitGo/BitGoJS#192]
Hello I’m trying to build a crypto instant exchange platform that works exactly like shapeshift. That's you have BTC and wants to get LTC. I'm also making use of bitgo.

How do I determine that this transaction is an on-chain transaction since it’s a trade happening inside the website and utilizing bitgo wallets.

**Comment by Xekyo** [comment]
If you're instantly paying out to the trading party, this would probably need on-chain transactions. If the customers hold their funds deposited in your service, you could have the trade settlement off-chain in your database, and would only need to perform on-chain transactions when the customer withdraws.

I'm closing this issue, since this line of inquiry is not related to this repository but should rather be directed at BitGo support.
