### ISSUE TITLE
Breaks superagent

### ISSUE THREAD

**Issue by olalonde** [BitGo/BitGoJS#23]
When requiring bitgo, my node process hangs which means that bitgo is probably opening some connection?

**Comment by olalonde** [comment]
Nevermind! the problem was with another module

**Comment by olalonde** [comment]
Oh the issue is that both bitgojs and my tests are using the supertest-as-promised module and this hangs one of my test for some reason.

**Comment by olalonde** [comment]
Ah, I guess this is the problem: https://github.com/BitGo/BitGoJS/blob/a8bec7b739e2eb56cb066b0771690bb027ef4b7d/src/bitgo.js#L30

**Comment by olalonde** [comment]
Requiring Bitgo will break any app that uses superagent, maybe there would be a more elegant way to do this than patching superagent globally?

**Comment by bpdavenport** [comment]
Thanks for debugging. Is there a way you can work around this for the moment? Is bitgo not installing its own version of superagent, because you have it installed as a peer dependency? Can you force bitgo to install its own superagent that would then not conflict? Perhaps maybe if we changed the version from ^1.4.0 to "1.4.0", then you could depend on a different version, which would force it to be installed.

**Comment by bpdavenport** [comment]
We will look at how to make this cleaner, but it may take a bit.

**Comment by olalonde** [comment]
Yes, it's using the superagent I have already npm installed.

```
$ node --version
v6.0.0
$ npm --version
3.8.6
```

**Comment by olalonde** [comment]
I think changing ^1.4.0 to "1.4.0" or if you published a fork of superagent under bitgo-superagent

**Comment by olalonde** [comment]
FWIW, Superagent will ship with promises soon: https://github.com/visionmedia/superagent/pull/925 (not on npm yet though)

**Comment by olalonde** [comment]
@bpdavenport this should fix my problem for now: https://github.com/BitGo/BitGoJS/pulls but ideally it would be better if bitgo didn't monkey patch superagent :)
