### ISSUE TITLE
Problem with a dependency that has malicious code

### ISSUE THREAD

**Issue by infra-membrane** [BitGo/BitGoJS#4047]
A security vulnerability has been identified in the BitGoJs SDK, specifically within one of its dependencies, 'resolve,' which uses 'monorepo-symlink-test' as a dependency. This package contained malicious code and was removed from the registry by the npm security team.
More info: https://www.npmjs.com/package/monorepo-symlink-test?activeTab=readme

node_modules/resolve/test/resolver/multirepo/package.json

{
  "name": "monorepo-symlink-test",
  "private": true,
  "version": "0.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "postinstall": "lerna bootstrap",
    "test": "node packages/package-a"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "jquery": "^3.3.1",
    "resolve": "../../../"
  },
  "devDependencies": {
    "lerna": "^3.4.3"
  }
}

**Comment by margueriteblair** [comment]
Hey there, so according to the resolve package itself, this is just a [false positive](https://github.com/browserify/resolve/issues/303) because the dependency is named the same thing. Also, snyk on our end doesn't detect any vulnerability, which substantiates resolve's note that the dependency of resolve is not the same as the one that NPM removed. 

Hope this helps!
