### ISSUE TITLE
Malware address check

### ISSUE THREAD

**Issue by singhvijayy** [BitGo/BitGoJS#47]
Hi, is the malware address list provided by BitGo api at **GET /api/v1/malware/bitcoin** supposed to be checked against **account** key values in **entries** object - **entries** object is itself a key in object obtained after querying BitGo api with **hash** received in webhook respone? (see below)

**Webhook response** -
{
...
hash: some_hash
...
}

**wallet.getTransaction({id: some_hash}) response** -
{
...
entries: [{account: some_address, value: some_btc_value}, ...]
...
}

What should malware addresses should be checked against, is not clearly mentioned in the BitGo api.

**Comment by bpdavenport** [comment]
This list should be used when SENDING bitcoin, to ensure you're not accidentally sending to one of these addresses. If you do send to one of these addresses, BitGo will block the tx. But it is better for the exchange customer to catch it prior to trying to send, so that (for example) other customers of the exchange sending to legitimate addresses are not affected by a failed multi-destination tx.
