### ISSUE TITLE
BitGo.prototype.calculateMinerFeeInfo deprecated

### ISSUE THREAD

**Issue by pgaucorp** [BitGo/BitGoJS#487]
What is the reason this functionality is deprecated from SDK and only accessible from Express?

**Comment by tylerlevine** [comment]
There are a few reasons, but the most relevant one is it's because we now have a better library for calculating transaction sizes: https://github.com/BitGo/unspents

To get from a transaction size to a miner fee, you just need to multiply by `feeRate / 1000`. (assuming a fee rate given in satoshis per virtual kilobyte).

Note that the express version of this call is also deprecated.
