### ISSUE TITLE
Methods that require authentication won't work client-side

### ISSUE THREAD

**Issue by gabrielfresco09** [BitGo/BitGoJS#704]
Trying to call any method that requires authentication throws an unauthorized exception if no proxy is defined and if it's then them throw `cannot use https proxy params while in browser`. [client-side]

## Environment Details
* **OS:** Linux Mint 19.1
* **Node Version:** v10.17.0
* **Npm Version:** 6.11.13
* **BitGoJS Version:** 9.6.2
* **BitGo Environment:** test

## Expected Behavior
Get a successful response with the desired data. 

## Current Behavior
Any method throws unauthenticated exception if proxy not specified. If one is, then all of them throw `cannot use https proxy params while in browser` 

## Possible Solution
Either support direct calls client-side or fix this proxy issue.

## Steps to Reproduce
1. Have importe BitGoJS.min.js client-side
2. define `const bitgo = new BitGoJS.BitGo({ accessToken: <access_token>, proxy: <your_proxy_address> })`

**Comment by jpcapurro-atixlabs** [comment]
Update: we tried to inspect the problem a little further, what we found is:
When running the following in the browser:
```
var bitgo = new BitGoJS.BitGo({
  env: 'test',
  accessToken:
    'v2x63a93ccddfffb4b9812cd21b008373ea7e669939911990af0845b51730c08313'
});

bitgo.session({}, console.log)
```

The browser does the following HTTP request:
```
[~]: curl 'https://test.bitgo.com/api/v1/user/session' -H 'Origin: http://localhost:8080' -H 'If-Modified-Since: Mon, 26 Jul 1997 05:00:00 GMT' -H 'Authorization: Bearer REDACTED' -H 'BitGo-Auth-Version: 2.0' -H 'HMAC: REDACTED' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36' -H 'Referer: http://localhost:8080/' -H 'BitGo-SDK-Version: 11.0.0' -H 'Auth-Timestamp: 1585077271467' --compressed
```

Which returns a HTTP 401 with the following payload:
```
{"error":"unauthorized","name":"Unauthorized","requestId":"REDACTED","context":{}}%
```

However, if we remove the `Origin` header (not in the browser, but with otherwise the same request via cURL)
```
[~]: curl 'https://test.bitgo.com/api/v1/user/session' -H 'If-Modified-Since: Mon, 26 Jul 1997 05:00:00 GMT' -H 'Authorization: Bearer REDACTED' -H 'BitGo-Auth-Version: 2.0' -H 'HMAC: REDACTED' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36' -H 'Referer: http://localhost:8080/' -H 'BitGo-SDK-Version: 11.0.0' -H 'Auth-Timestamp: 1585077271467' --compressed
```
We get a successful (expected) response.

Extra info
----------
- We import the SDK in the browser by sourcing the minified file with a `<src>` tag, as described in the [bitgo-browser-example](https://github.com/BitGo/bitgo-browser-example).

Questions
---------
- [  ] Is this behaviour expected?
- [  ] Where can we find more documentation related to how to run the SDK in the browser?
- [  ] Are we missing some kind of proxy? While we could strip this header with a HTTP proxy, the SDK rejects the `proxy` configuration key when instantiating it, so we're not sure what is the expected usage.

@tylerlevine we would appreciate if you could take a look at this, however we're open to asking for help in a different medium if that's more appropiate.

Thanks for your time :sparkles:

**Comment by tylerlevine** [comment]
Hey @jpcapurro-atixlabs, thanks for the additional information. You must be doing some local testing, which is probably why the browser sets the origin header the way it does.

We currently enforce that the origin is a bitgo domain in our auth handler, and I think that's why you are getting a 401 Unauthorized for your requests. If you have a requestId you could share, that would let me confirm that this is the case. Once the problem is identified, we can discuss some solutions.

**Comment by jpcapurro-atixlabs** [comment]
@tylerlevine we've contacted BitGo support (for reference, Gabe Frank replied to our emails) and are currently awaiting response
They said the issue had been forwarded to the engineering team.

If it makes things easier on your end, I'll provide here the request id that we gave to BitGo support (but I don't know if you should check it anyways, and I really don't want to waste any of your resources by having two people look at this issue 🙃):

```
curl 'https://test.bitgo.com/api/v1/user/session' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'BitGo-SDK-Version: 11.0.0' -H 'BitGo-Auth-Version: 2.0' -H 'If-Modified-Since: Mon, 26 Jul 1997 05:00:00 GMT' -H 'Auth-Timestamp: 1585174050115' -H 'Authorization: Bearer REDACTED' -H 'HMAC: REDACTED' -H 'Origin: http://localhost:8080' -H 'Connection: keep-alive' -H 'Referer: http://localhost:8080/' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'

{"error":"unauthorized","name":"Unauthorized","requestId":"ck87vpq0z0e48t2rzaen3l8zq","context":{}}
```

I'll, however, try to keep this issue updated in case anyone has the same problem in the future.

**Comment by tylerlevine** [comment]
Yeah, it's as I thought - the token is only good for the origin where it's created. Have you looked into doing an OAuth integration? Support should be able to help you with that.

**Comment by twtaylorbitgo** [comment]
Hi guys, our support will reach out to you about a solution around this. Please follow-up with support instead of here on GH.

**Comment by Lyana13** [comment]
Hello everyone. I'm experiencing the same problem with Origin header. Should I write to support too? As I see it's widespread problem ...
