### ISSUE TITLE
Unable to generate TETH Wallet

### ISSUE THREAD

**Issue by sachin-lalaworld** [BitGo/BitGoJS#77]
URL : http://localhost:3080/api/v2/teth/wallet/generate

Request : {"label":"TETH Wallet", "passphrase": "testeth"}

Response : 
{
    "error": "expecting enterprise when adding BitGo key",
    "message": "expecting enterprise when adding BitGo key"
}

**Comment by thomas4019** [comment]
Hi Sachin,
Ethereum wallets currently can only be created within an enterprise so you'll need to pass your enterprise id when creating an ETH wallet. If you haven't made an enterprise yet you can make one by selecting the "Create Organization" option in the user dropdown. Please review [our documentation about ethereum](https://www.bitgo.com/api/v2/#ethereum) because you will also need to fund the enterprise fee address which is explained there.

**Comment by CeoFred** [comment]
First the link you provided is wrong, it's broken.. Second, there is no way to see my enterprise ID from the dashboard neither can i create one
