### ISSUE TITLE
Facing problem while proccess the buy and sell orders

### ISSUE THREAD

**Issue by ravingalaxy** [BitGo/BitGoJS#78]
Actually we are integrating BitGo API for our multi user trading exchange , in which we required many wallets for our users. one wallet for each user. so when i trying process orders in my orderlist , for some times orders executed successfully but after some time  bitgo api is not give any response, is there any restriction on sending and receiving btc though api after some processing (Buy order and Sell order). let me know if there is any condition and also suggest me about the right way in which i can process and execute my exchange orders successfully without any restriction.

**Comment by thomas4019** [comment]
Hi ravingalaxy,
We have rate-limiting in place to ensure that our API so that may be an issue you're having. Since this not an issue with our code, please instead email support@bitgo.com and you can get prompt help there. Please provide the email of the account where you are seeing the issues, which environment (test or prod), some relevant wallet ids, and which endpoints of our API you are seeing issues with specifically. Thanks!
