### ISSUE TITLE
Can't Get Hash on Request

### ISSUE THREAD

**Issue by bobozar** [BitGo/BitGoJS#87]
What is the key to call from BitGo API to get from a webhook immediately an address receive BTC. 

From my ngrok, I saw this

```
{
    "hash": "26ba9cc3218962417f529803d82dd63850b895fbee74517dff",
    "type": "transaction",
    "coin": "bitcoin",
    "walletId": "2Mzb4KMAp"
}
```

So when I did the following in the 'hook callback url', I'm getting error. 500 Error.

```
1. txId  =  request.POST.get('hash')
2. txId = request.GET['hash']
3. txId = request.POST['hash']
```

How do I get the hash since all the above method failed. I'm using Python/Django.

**Comment by thomas4019** [comment]
Hi bobozar,
BitGo webhooks pass data in JSON format so you'll need to parse the message body. In Python the best way is probably json.loads(request.body) which returns a dictionary you can then get the 'hash' from. I'll look into making our documentation more clear about this.

**Comment by bobozar** [comment]
Thanks @thomas4019  But another thing is, why is Bitgo sending a receive transaction signal after it must have been successful the first time. For example, when I received BTC, BitGo triggered the hook and I updated the user wallet on my site, few mins later, BitGo sends another signal with the previous transaction and the user wallet on my site was updated again. This is not supposed to be like that. 

[08/Jan/2018 22:39:32] "POST /vc/bt_c/ HTTP/1.1" 200 4
[08/Jan/2018 22:39:32] "POST /vc/bt_c_one/ HTTP/1.1" 200 4
[08/Jan/2018 22:39:32] "POST /vc/bt_co_one/ HTTP/1.1" 200 4
[08/Jan/2018 22:39:32] "POST /vc/bt_co/ HTTP/1.1" 200 4

It should be one time! for each not twice.

**Comment by thomas4019** [comment]
Hi bobozar,
I think it is one of either one of two issues.
1) You have created duplicate webhooks. Please call our [list wallet webhooks](https://bitgo.github.io/bitgo-docs/#list-wallet-webhooks) and make sure that you don't have two webhooks for the same url on that wallet.
2) The block is confirming shortly after the tx is sent. Please read the section about the numConfirmations parameter to the webhook. It is expected that you will get two notifications unless you explicitly set a [numConfirmations](https://bitgo.github.io/bitgo-docs/#add-wallet-webhooks) on the webhook.

> If 0 or unspecified, requests will be sent to the callback endpoint will be called when the transaction is first seen and when it is confirmed


If neither of these solve your issue please provide the relevant wallet id so I can take a look. Also, this issue is not specifically related to our BitGoJS library, so for future issues please file a [support ticket](https://bitgo.freshdesk.com/support/tickets/new).
