### ISSUE TITLE
wallet.createAddress won't create segwit address if Ledger is being used

### ISSUE THREAD

**Issue by mautematico** [BitGo/BitGoJS#89]
If Ledger was used to create wallet,

This works as expected:
`wallet.generateAddress({ segwit: true, path: '/10/1' })`

Response being like this:

```
{ chainPath: '/10/1',
  path: '/10/1',
  chain: 10,
  index: 1,
  wallet: 'waaaaallet',
  redeemScript: '00scrriiipt',
  witnessScript: '52witnesScriiipt',
  outputScript: 'a91outputscriipt',
  address: '3FaaaDress' }

```

But, this won't:
wallet.createAddress({ chain: 10 })

```

{ address: '3-non-segwit-address',
    chain: 0,
    index: 8,
    path: '/0/8',
    redeemScript: '52redeemscript',
    wallet: '3waaalet' }
```

As you can see, expected path wash /10/*, but actual path was /0/8, i.e. legacy (non-segwit) external path.

Same code works as expected when wallet was not created with Ledger.
Any suggestions?
Is this a bug on the bitgo side?

**Comment by LeoKotschenreuther** [comment]
Hi @mautematico 
Wallets that were created with Ledger don't support SegWit. When you call generateAddress, the SDK creates a new address locally. Because the SDK doesn't know about the fact that your wallet was created with ledger it still generates you a SegWit address. When you call createAddress, the SDK makes a call to our server which knows that your wallet was created with ledger and hence makes the smart choice of creating you a non SegWit address.
